### ISSUE TITLE
Need Properties file for  coverity collector 

### ISSUE THREAD

**Issue by tarun-teja** [Hygieia/hygieia-codequality-coverity-collector#3]
I compiled and ran the collector according to the instructions but can't get any data . I checked db.collectors.find() collection and the coverity servers array is empty.

 I copied my properties file from  https://github.com/Hygieia/hygieia-codequality-coverity-collector and changed the values.

How do I add the coverity URL and credentials so that the collector may fetch data?

Thanks
Tarun

**Comment by rvema** [comment]
@fidelcoria-aa can you respond back?

**Comment by alzafacon** [comment]
Hi @tarun-teja as I mentioned in gitter you should add connection details from the Admin Configuration Page. It looks like below. 
![image](https://user-images.githubusercontent.com/41026947/59775091-2b31f000-9276-11e9-9352-f263cacf22d0.png)
After adding URL, username, and password the Coverity collector will use this configuration.

Here is where you can configure the coverity project&stream
![image](https://user-images.githubusercontent.com/41026947/59775782-5e28b380-9277-11e9-8c76-851a100f193b.png)

**Comment by tarun-teja** [comment]
Thanks @fidelcoria-aa . I was able to configure the Code Analysis Widget for Coverity. 

One caveat for everyone : This collector only collects security related info.
